const actionTypes = {
  TABTWO_REQUEST_INIT: "TABTWO_REQUEST_INIT",
  TABTWO_REQUEST_SUCCESS: "TABTWO_REQUEST_SUCCESS",
  TABTWO_REQUEST_ERROR: "TABTWO_REQUEST_ERROR",
  TABTWO_REQUEST_RESET: "TABTWO_REQUEST_RESET",
  TABTWO_REQUEST_LOAD_ERROR: 'TABTWO_REQUEST_LOAD_ERROR'
};

export { actionTypes };
