const actionTypes = {
  TABONE_REQUEST_INIT: "TABONE_REQUEST_INIT",
  TABONE_REQUEST_SUCCESS: "TABONE_REQUEST_SUCCESS",
  TABONE_REQUEST_ERROR: "TABONE_REQUEST_ERROR",
  TABONE_REQUEST_RESET: "TABONE_REQUEST_RESET",
  TABONE_REQUEST_LOAD_ERROR: 'TABONE_REQUEST_LOAD_ERROR'
};

export { actionTypes };
