export const actionTypes = {
  AUTH_REQUEST_INIT: "AUTH_REQUEST_INIT",
  AUTH_REQUEST_SUCCESS: "AUTH_REQUEST_SUCCESS",
  AUTH_REQUEST_FAILURE: "AUTH_REQUEST_FAILURE",
  AUTH_CLEAR_ERROR: "AUTH_CLEAR_ERROR",
  AUTH_RESET_STATE: "AUTH_RESET_STATE",
  AUTH_SELECTED_TERMINAL: "AUTH_SELECTED_TERMINAL",
};
